version: "3.8"

services:
  db:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_HOST: 'localhost'
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'dbpix'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - '3333:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

